### ISSUE TITLE
Cron Deamon Permission Error on rsync to netshare

### ISSUE THREAD

**Issue by Mandolorijan** [nano-bio/labbooks#28]
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/.postmaster.opts.yVS9KN" -> "labbooks_postgres-data/_data/postmaster.opts": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/.postmaster.pid.S25aCs" -> "labbooks_postgres-data/_data/postmaster.pid": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/1/.pg_internal.init.8nK3zE" -> "labbooks_postgres-data/_data/base/1/pg_internal.init": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.1259.OEvhbK" -> "labbooks_postgres-data/_data/base/16384/1259": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16399.lEXEFm" -> "labbooks_postgres-data/_data/base/16384/16399": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16408.Dcz32i" -> "labbooks_postgres-data/_data/base/16384/16408": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16415.age2uP" -> "labbooks_postgres-data/_data/base/16384/16415": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16430.3UmEwJ" -> "labbooks_postgres-data/_data/base/16384/16430": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16431.1VmGhH" -> "labbooks_postgres-data/_data/base/16384/16431": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16431_fsm.fWvezf" -> "labbooks_postgres-data/_data/base/16384/16431_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16435.aOqvc9" -> "labbooks_postgres-data/_data/base/16384/16435": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16437.76GnQL" -> "labbooks_postgres-data/_data/base/16384/16437": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16439.4vKGAA" -> "labbooks_postgres-data/_data/base/16384/16439": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16440.WtaJ8B" -> "labbooks_postgres-data/_data/base/16384/16440": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16444.3vlLWs" -> "labbooks_postgres-data/_data/base/16384/16444": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16446.oQbg47" -> "labbooks_postgres-data/_data/base/16384/16446": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16447.Gzo4iV" -> "labbooks_postgres-data/_data/base/16384/16447": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16451.nzXbN0" -> "labbooks_postgres-data/_data/base/16384/16451": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16476.TRDY30" -> "labbooks_postgres-data/_data/base/16384/16476": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16477.Zzrm1r" -> "labbooks_postgres-data/_data/base/16384/16477": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16489.Hz6dap" -> "labbooks_postgres-data/_data/base/16384/16489": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16490.eXXKwv" -> "labbooks_postgres-data/_data/base/16384/16490": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16491.yQxgfA" -> "labbooks_postgres-data/_data/base/16384/16491": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16503.6D7V4e" -> "labbooks_postgres-data/_data/base/16384/16503": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16504.P8gAYt" -> "labbooks_postgres-data/_data/base/16384/16504": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16505.9utGAx" -> "labbooks_postgres-data/_data/base/16384/16505": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16506.Qx8n4t" -> "labbooks_postgres-data/_data/base/16384/16506": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16506_fsm.gYme5N" -> "labbooks_postgres-data/_data/base/16384/16506_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16506_vm.nyuJnc" -> "labbooks_postgres-data/_data/base/16384/16506_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16513.tAq4In" -> "labbooks_postgres-data/_data/base/16384/16513": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16525.tBOCVV" -> "labbooks_postgres-data/_data/base/16384/16525": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16526.rEYCiB" -> "labbooks_postgres-data/_data/base/16384/16526": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16588.eziZhK" -> "labbooks_postgres-data/_data/base/16384/16588": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16595.MkwWtC" -> "labbooks_postgres-data/_data/base/16384/16595": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16738.dE56Fw" -> "labbooks_postgres-data/_data/base/16384/16738": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16743.60qRTW" -> "labbooks_postgres-data/_data/base/16384/16743": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16744.2DoIcQ" -> "labbooks_postgres-data/_data/base/16384/16744": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16745.U8Ig7c" -> "labbooks_postgres-data/_data/base/16384/16745": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16746.qJBHes" -> "labbooks_postgres-data/_data/base/16384/16746": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16747.AdVTQg" -> "labbooks_postgres-data/_data/base/16384/16747": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16748.COEeFv" -> "labbooks_postgres-data/_data/base/16384/16748": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16749.P9Pe0k" -> "labbooks_postgres-data/_data/base/16384/16749": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16750.LCCJGD" -> "labbooks_postgres-data/_data/base/16384/16750": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16751.ZiG7xW" -> "labbooks_postgres-data/_data/base/16384/16751": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16752.P1KNWc" -> "labbooks_postgres-data/_data/base/16384/16752": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16753.SsOKkS" -> "labbooks_postgres-data/_data/base/16384/16753": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16754.S7DEQg" -> "labbooks_postgres-data/_data/base/16384/16754": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16755.vGRrH1" -> "labbooks_postgres-data/_data/base/16384/16755": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16860.mqxIn0" -> "labbooks_postgres-data/_data/base/16384/16860": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16874.AWcBGZ" -> "labbooks_postgres-data/_data/base/16384/16874": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16877.svOVzr" -> "labbooks_postgres-data/_data/base/16384/16877": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16878.bsAbbQ" -> "labbooks_postgres-data/_data/base/16384/16878": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16879.Lilbyx" -> "labbooks_postgres-data/_data/base/16384/16879": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16880.B58SGg" -> "labbooks_postgres-data/_data/base/16384/16880": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16893.soIF5u" -> "labbooks_postgres-data/_data/base/16384/16893": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16896.6n9lGP" -> "labbooks_postgres-data/_data/base/16384/16896": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16897.1HxgMw" -> "labbooks_postgres-data/_data/base/16384/16897": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16898.Q9DVsF" -> "labbooks_postgres-data/_data/base/16384/16898": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16899.j124Dy" -> "labbooks_postgres-data/_data/base/16384/16899": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16903.yZLMHP" -> "labbooks_postgres-data/_data/base/16384/16903": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16906.oIqWRk" -> "labbooks_postgres-data/_data/base/16384/16906": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16907.p0doCY" -> "labbooks_postgres-data/_data/base/16384/16907": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16942.5Ln6Dc" -> "labbooks_postgres-data/_data/base/16384/16942": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16975.F64lnY" -> "labbooks_postgres-data/_data/base/16384/16975": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16984.grLPgh" -> "labbooks_postgres-data/_data/base/16384/16984": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16987.xSByC3" -> "labbooks_postgres-data/_data/base/16384/16987": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16988.WmjH3R" -> "labbooks_postgres-data/_data/base/16384/16988": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16989.taEqAH" -> "labbooks_postgres-data/_data/base/16384/16989": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.16990.QFeh6a" -> "labbooks_postgres-data/_data/base/16384/16990": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17214.sA0xXV" -> "labbooks_postgres-data/_data/base/16384/17214": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17247.1qbldH" -> "labbooks_postgres-data/_data/base/16384/17247": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17250.BBc1Tq" -> "labbooks_postgres-data/_data/base/16384/17250": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17251.Emng77" -> "labbooks_postgres-data/_data/base/16384/17251": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17302.M7F5br" -> "labbooks_postgres-data/_data/base/16384/17302": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17302_fsm.28VZGB" -> "labbooks_postgres-data/_data/base/16384/17302_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17302_vm.lozfCf" -> "labbooks_postgres-data/_data/base/16384/17302_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17307.jdmOcy" -> "labbooks_postgres-data/_data/base/16384/17307": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17308.iF0v9K" -> "labbooks_postgres-data/_data/base/16384/17308": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17309.jubmdc" -> "labbooks_postgres-data/_data/base/16384/17309": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17310.SENaoV" -> "labbooks_postgres-data/_data/base/16384/17310": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17311.LEpS1S" -> "labbooks_postgres-data/_data/base/16384/17311": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17312.GASNUW" -> "labbooks_postgres-data/_data/base/16384/17312": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17313.wckTn3" -> "labbooks_postgres-data/_data/base/16384/17313": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17314.B4FJ8m" -> "labbooks_postgres-data/_data/base/16384/17314": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17315.THE3fu" -> "labbooks_postgres-data/_data/base/16384/17315": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17819.tEsb1V" -> "labbooks_postgres-data/_data/base/16384/17819": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17819_fsm.doVLF3" -> "labbooks_postgres-data/_data/base/16384/17819_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17819_vm.WQyNMi" -> "labbooks_postgres-data/_data/base/16384/17819_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17824.NnqnjC" -> "labbooks_postgres-data/_data/base/16384/17824": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17826.WRs2Jz" -> "labbooks_postgres-data/_data/base/16384/17826": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.17827.FkybpK" -> "labbooks_postgres-data/_data/base/16384/17827": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18373.nFytyM" -> "labbooks_postgres-data/_data/base/16384/18373": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18385.Fq1FoU" -> "labbooks_postgres-data/_data/base/16384/18385": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18404.hDQaLx" -> "labbooks_postgres-data/_data/base/16384/18404": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18407.EYnSi3" -> "labbooks_postgres-data/_data/base/16384/18407": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18408.RhLUWU" -> "labbooks_postgres-data/_data/base/16384/18408": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18411.1LWtVX" -> "labbooks_postgres-data/_data/base/16384/18411": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18416.83FKeD" -> "labbooks_postgres-data/_data/base/16384/18416": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18417.5oNdzy" -> "labbooks_postgres-data/_data/base/16384/18417": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18418.QxN1yc" -> "labbooks_postgres-data/_data/base/16384/18418": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18420.HUXfm2" -> "labbooks_postgres-data/_data/base/16384/18420": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18420_fsm.Bbs6HA" -> "labbooks_postgres-data/_data/base/16384/18420_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18420_vm.BIdAEU" -> "labbooks_postgres-data/_data/base/16384/18420_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18425.ejkltH" -> "labbooks_postgres-data/_data/base/16384/18425": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18426.TM2An6" -> "labbooks_postgres-data/_data/base/16384/18426": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18504.IxraQA" -> "labbooks_postgres-data/_data/base/16384/18504": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18517.O2EFgc" -> "labbooks_postgres-data/_data/base/16384/18517": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18536.Lw6fkn" -> "labbooks_postgres-data/_data/base/16384/18536": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18539.svvPnH" -> "labbooks_postgres-data/_data/base/16384/18539": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18540.MZIhat" -> "labbooks_postgres-data/_data/base/16384/18540": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18552.1vXkNo" -> "labbooks_postgres-data/_data/base/16384/18552": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18552_fsm.DwBDdP" -> "labbooks_postgres-data/_data/base/16384/18552_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18552_vm.FtPUNE" -> "labbooks_postgres-data/_data/base/16384/18552_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18557.R7kIio" -> "labbooks_postgres-data/_data/base/16384/18557": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18558.KNcBOO" -> "labbooks_postgres-data/_data/base/16384/18558": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18559.MxjUjj" -> "labbooks_postgres-data/_data/base/16384/18559": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18561.B7KUiV" -> "labbooks_postgres-data/_data/base/16384/18561": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18561_fsm.5tiYwx" -> "labbooks_postgres-data/_data/base/16384/18561_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18566.PlcLkb" -> "labbooks_postgres-data/_data/base/16384/18566": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18567.usM9dq" -> "labbooks_postgres-data/_data/base/16384/18567": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.18568.KqoT6r" -> "labbooks_postgres-data/_data/base/16384/18568": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2619.MZXcgk" -> "labbooks_postgres-data/_data/base/16384/2619": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2619_fsm.GCKRpi" -> "labbooks_postgres-data/_data/base/16384/2619_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2619_vm.dXgFvz" -> "labbooks_postgres-data/_data/base/16384/2619_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2696.tJwQqF" -> "labbooks_postgres-data/_data/base/16384/2696": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2840.lb2LMM" -> "labbooks_postgres-data/_data/base/16384/2840": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2840_fsm.8i5R2w" -> "labbooks_postgres-data/_data/base/16384/2840_fsm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2840_vm.Ckk8lv" -> "labbooks_postgres-data/_data/base/16384/2840_vm": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.2841.56YY7J" -> "labbooks_postgres-data/_data/base/16384/2841": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/16384/.pg_internal.init.SprLOW" -> "labbooks_postgres-data/_data/base/16384/pg_internal.init": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/base/5/.pg_internal.init.Yu4C45" -> "labbooks_postgres-data/_data/base/5/pg_internal.init": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/global/.pg_control.EpOBt8" -> "labbooks_postgres-data/_data/global/pg_control": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/global/.pg_internal.init.JhOkAD" -> "labbooks_postgres-data/_data/global/pg_internal.init": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_logical/.replorigin_checkpoint.qT6K3B" -> "labbooks_postgres-data/_data/pg_logical/replorigin_checkpoint": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_multixact/offsets/.0000.8z5L6D" -> "labbooks_postgres-data/_data/pg_multixact/offsets/0000": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_subtrans/.0000.vNMxcZ" -> "labbooks_postgres-data/_data/pg_subtrans/0000": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_wal/.000000010000000000000012.1KDr7G" -> "labbooks_postgres-data/_data/pg_wal/000000010000000000000012": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_wal/.000000010000000000000013.Tz7tzq" -> "labbooks_postgres-data/_data/pg_wal/000000010000000000000013": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_wal/.000000010000000000000014.TrDtqM" -> "labbooks_postgres-data/_data/pg_wal/000000010000000000000014": Permission denied (13)
rsync: rename "/media/netshare/Backups/c744-labbooks/labbooks_postgres-data/_data/pg_xact/.0000.ISlE7O" -> "labbooks_postgres-data/_data/pg_xact/0000": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]

**Comment by Mandolorijan** [comment]
This error occurs when the daily backup is made (every day at 1:42 am ). I tried to solve this error by asking Arntraud to give the labbooks-C-number (c7441148) the DELETE and MODIFY rights on the netshare server. She did this on Tue. 22.08.2023, however it did not change the error messages in the first moment. On Sa. 26.08.2023 though, the error message changed as follows.

**Comment by Mandolorijan** [comment]
/bin/bash: /srv/labbooks/backup-and-restore/backup-daily.sh: Permission denied

**Comment by Graf-Zahl** [comment]
Solved by adding into `/etc/samba/smb.conf` under section `[global]`:
```
inherit owner=yes
inherit permissions=yes
```
And reboot the system.
